const configValues = {
    states: {
      "Alabama": "AL",
      "Alaska": "AK",
      "Arizona": "AZ",
      "Arkansas": "AR",
      "Armed Forces Africa": "AE",
      "Armed Forces Americas": "AA",
      "Armed Forces Canada": "AE",
      "Armed Forces Europe": "AE",
      "Armed Forces Middle East": "AE",
      "Armed Forces Pacific": "AP",
      "California": "CA",
      "Colorado": "CO",
      "Connecticut": "CT",
      "Delaware": "DE",
      "District of Columbia": "DC",
      "Federated States Of Micronesia": "FM",
      "Florida": "FL",
      "Georgia": "GA",
      "Guam": "GU",
      "Hawaii": "HI",
      "Idaho": "ID",
      "Illinois": "IL",
      "Indiana": "IN",
      "Iowa": "IA",
      "Kansas": "KS",
      "Kentucky": "KY",
      "Louisiana": "LA",
      "Maine": "ME",
      "Marshall Islands": "MH",
      "Maryland": "MD",
      "Massachusetts": "MA",
      "Michigan": "MI",
      "Minnesota": "MN",
      "Mississippi": "MS",
      "Missouri": "MO",
      "Montana": "MT",
      "Nebraska": "NE",
      "Nevada": "NV",
      "New Hampshire": "NH",
      "New Jersey": "NJ",
      "New Mexico": "NM",
      "New York": "NY",
      "North Carolina": "NC",
      "North Dakota": "ND",
      "Northern Mariana Islands": "MP",
      "Ohio": "OH",
      "Oklahoma": "OK",
      "Oregon": "OR",
      "Palau": "PW",
      "Pennsylvania": "PA",
      "Puerto Rico": "PR",
      "Rhode Island": "RI",
      "South Carolina": "SC",
      "South Dakota": "SD",
      "Tennessee": "TN",
      "Texas": "TX",
      "Utah": "UT",
      "Vermont": "VT",
      "Virgin Islands": "VI",
      "Virginia": "VA",
      "Washington": "WA",
      "West Virginia": "WV",
      "Wisconsin": "WI",
      "Wyoming": "WY"
    },
  
    combosku: {
      "C": "100",
      "S": "101",
      "R": "102",
      "V": "103",
      "H": "104",
      "X": "105",
      "Y": "106",
      "Z": "107",
      "CC": "200",
      "SS": "201",
      "RR": "202",
      "VV": "203",
      "HH": "204",
      "XX": "205",
      "CS": "206",
      "CR": "207",
      "CV": "208",
      "CH": "209",
      "CX": "210",
      "SR": "211",
      "SV": "212",
      "SH": "213",
      "SX": "214",
      "RV": "215",
      "RH": "216",
      "RX": "217",
      "VH": "218",
      "VX": "219",
      "HX": "220",
      "YY": "221",
      "YZ": "222",
      "SY": "223",
      "RY": "224",
      "VY": "225",
      "HY": "226",
      "XY": "227",
      "ZZ": "228",
      "SZ": "229",
      "RZ": "230",
      "VZ": "231",
      "HZ": "232",
      "XZ": "233",
      "CY": "234",
      "CE": "235",
      "CZ": "236",
      "CA": "237",
      "CN": "238",
      "SE": "239",
      "SA": "240",
      "SN": "241",
      "RE": "242",
      "RA": "243",
      "RN": "244",
      "VE": "245",
      "VA": "246",
      "VN": "247",
      "HE": "248",
      "HA": "249",
      "HN": "250",
      "XE": "251",
      "XA": "252",
      "XN": "253",
      "YE": "254",
      "YA": "255",
      "YN": "256",
      "ZE": "257",
      "ZA": "258",
      "ZN": "259",
      "EE": "260",
      "EA": "261",
      "EN": "262",
      "AA": "263",
      "AN": "264",
      "NN": "265"
    },
  
    pizzaPackSkuOrder: ["C", "E", "S", "A", "R", "N", "M", "B", "I", "V", "H", "L", "X", "Y", "Z"],
  
    ghostBins: ([
      "LOUS-2DD", "LOUS-4DD", "LOUS-6DD",
      "LOUS-2TH1DD", "LOUS-2TH5DD", "LOUS-4TH",
      "LOUS-6TH", "LOUS-6DDTH", "LOUS-2TH5DD", "LOUS-7TH"
    ])
  };
  
  module.exports = configValues;
  