service: demo-toc
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    CURRENT_STAGE: ${sls:stage}
    CONFIG_VALUES_TABLE: ${self:custom.configValuesTablename}
    EI_CLOUD_ACC_NAME: ${env:EI_CLOUD_ACC_NAME}
    EI_CLOUD_ACC_ID: ${env:EI_CLOUD_ACC_ID}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.configValuesTablename}"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
  setConfig:
    handler: updateConfigTable.handler
    events:
      - http:
          method: post
          path: /seed-config-values
          cors: true
  getConfig:
    handler: getConfig.handler
    events:
      - http:
          method: get
          path: /config-values
          cors: true
 
  updateConfig:
    handler: updateTable.handler
    events:
      - http:
          method: put
          path: /config-values
          cors: true
resources:
  Resources:
    configValuesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.configValuesTablename}
        AttributeDefinitions:
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: value
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  configValuesTablename: configValues-${self:provider.stage}
