service: demo-toc
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    CURRENT_STAGE: ${sls:stage}
    CONFIG_VALUES_TABLE: ${self:custom.configValuesTablename}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.configValuesTablename}"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
  getConfig:
    handler: getConfig.handler
    events:
      - http:
          path: config
          method: get
          cors: true
  setConfig:
    handler: updateConfigTable.handler
    events:
      - http:
          path: config
          method: post
          cors: true

resources:
  Resources:
    configValuesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.configValuesTablename}
        AttributeDefinitions:
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: value
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  configValuesTablename: configValues-${self:provider.stage}

# custom:
#   scripts:
#         hooks:
#           'after:deploy:deploy': npm run update-config


# plugins:
# - serverless-plugin-scripts