version: 2.1

orbs:
  node: circleci/node@4.7.0

aliases:
  - &node_executor
    - docker:
        - image: cimg/node:14.19.1

jobs:

  build:
    <<: *node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    <<: *node_executor
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Serverless framework
          command: npm install serverless
      - run:
        name: Set deployment env vars
        command: |
          ENV_FILE='.env'
          touch $ENV_FILE
          echo EI_CLOUD_ACC_ID=$EI_CLOUD_ACC_ID >> $ENV_FILE
          echo EI_CLOUD_ACC_NAME=$EI_CLOUD_ACC_NAME >> $ENV_FILE
      - run:
          name: Deploy serverless package
          command: npx serverless deploy --stage << parameters.stage >>
  update-dynamodb:
    parameters:
      stage:
        type: string
        default: dev
    docker:
      - image: circleci/python:3.8
    steps:
      - run: 
          name: Install AWS CLI
          command: |
            sudo apt-get -y update
            sudo apt-get -y install awscli
      - run:
          name: Invoke setConfig Lambda function
          command: aws lambda invoke --function-name demo-toc-<< parameters.stage >>-setConfig --region ap-south-1 output.txt

workflows:
  dev_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          context: toc-nonprod-kirtan
          filters:
            branches:
              only: main
      - update-dynamodb:
          requires:
            - deploy
          filters:
            branches:
              only: main

  prod_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - build
          stage: prod
          context: toc-prod-kirtan
          filters:
            branches:
              only: release
      - update-dynamodb:
          requires:
            - deploy
          filters:
            branches:
              only: release
          stage: prod
