version: 2.1

orbs:
  node: circleci/node@4.7.0

aliases:
  - &node_executor
    - docker:
        - image: cimg/node:14.19.1

jobs:

  build:
    <<: *node_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    <<: *node_executor
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Set deployment env vars
          command: |
            # Add your environment variable setup here if needed
            # For example:
            # export AWS_ACCESS_KEY_ID=<your-access-key-id>
            # export AWS_SECRET_ACCESS_KEY=<your-secret-access-key>
      - run:
          name: Install Serverless framework
          command: npm install serverless
      - run:
          name: Deploy serverless package
          command: npx serverless deploy --stage << parameters.stage >>


  update_config:
    <<: *node_executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Update config values table
          command: npm run update-config

workflows:

  main_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
      - update_config:
          requires:
            - deploy
          filters:
            branches:
              only: main
